kernel: sched: ems: Add missing implicit int
* Fixes:
../kernel/sched/ems/sysbusy.c:43:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static cpn_next_cpu[VENDOR_NR_CPUS] = { [0 ... VENDOR_NR_CPUS - 1] = -1 };
~~~~~~ ^

Change-Id: I9f945d03171346fe023be6f594a0253e6ee5d28f