sound: soc: rt56xx: use different name for workqueues
We get a linker error because they both try to start work with the same name when made inbuilt.

ld.lld: error: duplicate symbol: exynos_register_card_work
>>> defined in sound/built-in.a(soc/samsung/exynos8825_audio.o)
>>> defined in sound/built-in.a(soc/samsung/exynos8825_rt5691.o)

ld.lld: error: duplicate symbol: exynos_register_card_work
>>> defined in sound/built-in.a(soc/samsung/exynos8825_audio.o)
>>> defined in sound/built-in.a(soc/samsung/exynos8825_rt5665.o)

Signed-off-by: Nahuel Gómez <nahuelgomez329@gmail.com>